name: temp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^1.1.0
  flutter:
    sdk: flutter

  url_launcher: ^5.5.0
  universal_html: ^1.2.3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: GitHubLogo
      fonts:
      - asset: resources/fonts/GitHubLogo.ttf
      
    - family: LinkdInLogo
      fonts:
      - asset: resources/fonts/LinkdInLogo.ttf

  assets:
    - resources/images/avatar/
    - resources/images/
    - resources/misc/
